Fix build error caused by typegram
```
Error: node_modules/typegram/index.d.ts(10,1): error TS2308: Module "./default" has already exported a member named 'Ret'. Consider explicitly re-exporting to resolve the ambiguity.
```
See https://github.com/KnorpelSenf/typegram/issues/43